# Generated by Django 4.1 on 2022-09-26 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("components", "0001_initial"),
        ("media", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewDesignRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "new_design_requests",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("sold_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("publish_date", models.DateField()),
                ("sold_date", models.DateField()),
                ("is_gift", models.BooleanField(default=False)),
                ("is_replacement", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
            options={
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=6)),
                ("note", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "product_sizes",
            },
        ),
        migrations.CreateModel(
            name="ProductStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=6)),
                ("note", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "product_statuses",
            },
        ),
        migrations.CreateModel(
            name="ProductStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "product_styles",
            },
        ),
        migrations.CreateModel(
            name="ProductRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_refunds",
            },
        ),
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=6)),
                ("note", models.CharField(max_length=200)),
                (
                    "media_thumbnail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="media.media"
                    ),
                ),
            ],
            options={
                "db_table": "product_colors",
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("note", models.CharField(max_length=200)),
                (
                    "parent_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productcategory",
                    ),
                ),
            ],
            options={
                "db_table": "product_categories",
            },
        ),
        migrations.CreateModel(
            name="ProductBlueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productcategory",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productcolor",
                    ),
                ),
                (
                    "component",
                    models.ManyToManyField(to="components.componentblueprint"),
                ),
                (
                    "fabric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="components.fabric",
                    ),
                ),
                ("media", models.ManyToManyField(to="media.media")),
                (
                    "new_version_of",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_version_of_design",
                        to="products.productblueprint",
                    ),
                ),
                (
                    "part_of",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_of_assembly",
                        to="products.productblueprint",
                    ),
                ),
                (
                    "size_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productsize",
                    ),
                ),
                (
                    "style_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productstyle",
                    ),
                ),
            ],
            options={
                "db_table": "product_blueprints",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="product_blueprint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productblueprint",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="reserved_for",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.productstatus"
            ),
        ),
    ]
