# Generated by Django 4.1 on 2022-09-26 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("warehouses", "0001_initial"),
        ("products", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="warehouse_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="warehouses.warehouse"
            ),
        ),
        migrations.AddField(
            model_name="newdesignrequest",
            name="product_blueprint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productblueprint",
            ),
        ),
        migrations.AddField(
            model_name="newdesignrequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customers.customer"
            ),
        ),
    ]
