# Generated by Django 4.1 on 2022-09-27 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcostprice",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
    ]
