# Generated by Django 4.1 on 2022-09-27 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "package_statuses",
            },
        ),
        migrations.CreateModel(
            name="ShippingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
            ],
            options={
                "db_table": "shipping_items",
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
            ],
            options={
                "db_table": "shipping_methods",
            },
        ),
        migrations.CreateModel(
            name="TrackNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "track_numbers",
            },
        ),
        migrations.CreateModel(
            name="TrackNumberHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField()),
                ("place", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "track_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="packages.tracknumber",
                    ),
                ),
            ],
            options={
                "db_table": "track_numbers_history",
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipped_at", models.DateTimeField()),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
                ("weight", models.FloatField()),
                ("sizes", models.CharField(max_length=32)),
                ("ship_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.address",
                    ),
                ),
                ("order", models.ManyToManyField(to="orders.order")),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
                (
                    "shipping_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="packages.shippingitem",
                    ),
                ),
                (
                    "shipping_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="packages.shippingmethod",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="packages.packagestatus",
                    ),
                ),
                (
                    "track_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="packages.tracknumber",
                    ),
                ),
            ],
            options={
                "db_table": "packages",
            },
        ),
    ]
