# Generated by Django 4.1 on 2022-09-26 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentBlueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("is_active", models.BooleanField(default=False)),
                ("note", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "component_blueprints",
            },
        ),
        migrations.CreateModel(
            name="ComponentColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=6)),
                ("note", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "component_colors",
            },
        ),
        migrations.CreateModel(
            name="FabricCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "fabric_categories",
            },
        ),
        migrations.CreateModel(
            name="FabricTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "fabric_types",
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("link", models.CharField(max_length=1024)),
            ],
            options={
                "db_table": "shops",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=6)),
                ("note", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "units",
            },
        ),
        migrations.CreateModel(
            name="Fabric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="components.fabriccategories",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="components.fabrictypes",
                    ),
                ),
            ],
            options={
                "db_table": "fabrics",
            },
        ),
        migrations.CreateModel(
            name="ComponentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=6)),
                ("note", models.CharField(max_length=200)),
                (
                    "media_thumbnail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="media.media"
                    ),
                ),
            ],
            options={
                "db_table": "component_types",
            },
        ),
        migrations.CreateModel(
            name="ComponentPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=8)),
                ("date", models.DateField()),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="components.shop",
                    ),
                ),
            ],
            options={
                "db_table": "component_prices",
            },
        ),
        migrations.CreateModel(
            name="ComponentInStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "component_blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="components.componentblueprint",
                    ),
                ),
            ],
            options={
                "db_table": "components_in_stock",
            },
        ),
    ]
