# Generated by Django 4.1 on 2022-09-26 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("warehouses", "0001_initial"),
        ("components", "0001_initial"),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentinstock",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="warehouses.warehouse"
            ),
        ),
        migrations.AddField(
            model_name="componentcolor",
            name="media_thumbnail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="media.media"
            ),
        ),
        migrations.AddField(
            model_name="componentblueprint",
            name="color",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="components.componentcolor",
            ),
        ),
        migrations.AddField(
            model_name="componentblueprint",
            name="media_thumbnail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="media.media"
            ),
        ),
        migrations.AddField(
            model_name="componentblueprint",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="components.componenttype",
            ),
        ),
    ]
