# Generated by Django 4.1 on 2022-09-26 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "media",
            },
        ),
        migrations.CreateModel(
            name="MediaFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=6)),
                ("note", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "media_folders",
            },
        ),
        migrations.CreateModel(
            name="MediaType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=6)),
                ("note", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "media_types",
            },
        ),
        migrations.CreateModel(
            name="MediaTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=6)),
                ("note", models.CharField(max_length=200)),
                ("media", models.ManyToManyField(to="media.media")),
            ],
            options={
                "db_table": "media_tags",
            },
        ),
        migrations.AddField(
            model_name="media",
            name="folder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="media.mediafolder"
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="media.mediatype"
            ),
        ),
    ]
